#MariaDB Database (Hausverwaltung)
version: '3.8'

services:
  mariadb:
    image: mariadb:11.5
    container_name: hausverwaltung_db
    environment:
      MYSQL_ROOT_PASSWORD: team8
      MYSQL_DATABASE: hausverwaltung
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: